### PR TITLE
Allow separate cardiac and resp files in BIDS format

### PR DESCRIPTION
**Pull request by alexsayal**
Solving #164 :
Made the import of the .tsv files possible with different sampling rates for cardiac and resp signals. I used linear interpolation to replace the NaNs and upscaled the respiratory signal, replicating what happens when using the .log files.

The output confound matrix is very similar to what the toolbox returns with the .log files.

### CODE REVIEW

**Comment by mrikasper** [comment]
Dear Alex,

Thank you so much for providing this improvement.

I will try to include it into the next PhysIO release (probably in March). In order to do so, I would like to create an integration test that checks the results of this BIDS reader. This would need your two separate BIDS input files and an output `physio.mat`.

Would you be able to share this data with me?

Furthermore, could you please also add a version of the [Contributor License Agreement](https://github.com/translationalneuromodeling/tapas/blob/master/Contributor-License-Agreement.md) file to this pull request that has a table row with your name and info inserted. I have explained the rationale for that [here](https://github.com/translationalneuromodeling/tapas/issues/89#issuecomment-614404341) and [here](https://github.com/translationalneuromodeling/tapas/issues/11#issuecomment-435213894).

Thank you very much again and all the best,
Lars

**Comment by alexsayal** [comment]
Hello Lars,

Sorry for the delay, here are the files you requested.

All the best,

[physioBIDSfiles.zip](https://github.com/translationalneuromodeling/tapas/files/7979363/physioBIDSfiles.zip)

**Comment by mrikasper** [comment]
Great, thank you, Alexandre!

I will get back to you when I have setup the test.

All the best,
Lars

**Comment by mrikasper** [comment]
Merging into development for unit testing

**Comment by mrikasper** [comment]
Dear Alexandre @alexsayal,

I have now created a unit test using your logfiles and saved results, but there are some small discrepancies between those outputs and the runs on my machine that I am trying to track down. Do you happen to know with which version of PhysIO you ran the tests? I deducted it has to be before `R2020a-v7.3.2`, because there is no `physio.version` variable in your output.

Thank you and all the best,
Lars

**Comment by alexsayal** [comment]
Hello @mrikasper ,

Something very strange happened, the physio.mat I sent was in fact generated using version `R2019-v7.2.0`... although I forked the latest `R2021a-v8.0.1` 🤯 

Anyway, I re-send the output, now sure I am using the latest version. Sorry for this.

[newversion.zip](https://github.com/translationalneuromodeling/tapas/files/8413593/newversion.zip)

**Comment by mrikasper** [comment]
Dear @alexsayal,

Thank you for getting back to me so swiftly! And no worries, that's exactly why I am writing the tests :-) What could have happened is that the PhysIO version used with SPM was still in the path (the one you have to put in `spm12/toolbox`) and shadowed your development version.

One more thing: I have to check the files you sent, but one thing I noticed when I was rerunning on my machine was that the cut-out of unused data was at the end of the whole time series before (see screenshot with `v7.2`), but is now at the beginning (see screenshot with `v8.1`). Since you specified the `StartTime` in the `.json` file as `-6.574`, i.e., logging starts 6.5 s before the scan, I believe the new version does the correct thing (also consistent with `align_scan = 'first'`, though that should have no meaning here) - is that true?

Thank you for your help and continued input,
Lars

image

image

**Comment by alexsayal** [comment]
Hello @mrikasper ,

Yes, cutting-out tics at the beginning of the acquisition is the correct approach. I have verified this on the original .log files as well, since the `_Info` file tells us the tic that corresponds to the first volume/slice and there are several tics on the `_RESP` and `_PULS´ files before that tic - exactly 6.57 seconds of data.

**Comment by mrikasper** [comment]
Dear Alexandre,

Great, thank you so much for checking and sending the updated results - I am happy to report the new integration tests run through here on my machine with identical results, so we can include your improvements into the next release.

One more question: I think the direct comparison with the Siemens log is a useful additional cross-over test, so that we can check consistency between the two read-ins. Would you be willing to share the `_Info`, `_RESP` and `_PULS` files with me as well, so that I can set up this test?

Thank you once again and all the best,
Lars

**Comment by alexsayal** [comment]
Dear @mrikasper, I am glad to hear that.

Of course, I attach the `.log` files here:

[Physio_20190114_145703_d056ae5f-9ba2-4a7b-8288-838f01ea258d_RESP.log](https://github.com/translationalneuromodeling/tapas/files/8419450/Physio_20190114_145703_d056ae5f-9ba2-4a7b-8288-838f01ea258d_RESP.log)
[Physio_20190114_145703_d056ae5f-9ba2-4a7b-8288-838f01ea258d_PULS.log](https://github.com/translationalneuromodeling/tapas/files/8419452/Physio_20190114_145703_d056ae5f-9ba2-4a7b-8288-838f01ea258d_PULS.log)
[Physio_20190114_145703_d056ae5f-9ba2-4a7b-8288-838f01ea258d_Info.log](https://github.com/translationalneuromodeling/tapas/files/8419453/Physio_20190114_145703_d056ae5f-9ba2-4a7b-8288-838f01ea258d_Info.log)

All the best,

**Comment by mrikasper** [comment]
Thank you, @alexsayal,

that's great! I will incorporate it into the testing framework, but maybe it only makes it into the release after next.

All the best,
Lars

**Pull request merged**
