### PR TITLE
Update Contributor-License-Agreement.md

### PR DESCRIPTION
**Pull request by SaskiaBollmann**
Added my name to the contributor table.

### CODE REVIEW

**Comment by mms-neuro** [comment]
Sorry, that was the old version - now we have the updated version of the CLA online (again on the development branch). Could you open a new pull request against that version? Thank you!

**Comment by mrikasper** [comment]
Hi @mms-neuro,

just to confirm: the new CLA does not include any of the old signees...Is this on purpose? The problem I see with that is that until they do another pull request, it's not documented in the current version of the code that these are external contributors, even though their code is still in the code base.

Wouldn't it be better to have the old table also in the CLA and make a comment that these people undersigned a slightly different version of the CLA?

Best,
Lars

**Comment by mrikasper** [comment]
Maybe something like this, adding a version column to the table, and also referring to the current CLA version somewhere (e.g., at the start):

Contributor License Agreement
=============================
_Version 1.1 (2022-09-01)_

This AGREEMENT is made by and between the 

University of Zurich, Rämistrasse 71, 8006 Zürich, Switzerland   
(hereinafter referred to as "University of Zurich")

and 

each GitHub User listed in the following table:   

Name                     | Company/Institution/Address        | City      | Country | E-Mail/GitHub Username | CLA version signed
------------------------ | ---------------------------------- | --------- | ------- | ----------------------|---------------------
Lars Kasper              | TNU, University of Zurich          | Zurich    | CH      | mrikasper | 1.0
Eduardo Aponte           | TNU, University of Zurich          | Zurich    | CH      | tnutapas | 1.0
Daniel Hoffmann Ayala    | Technical University               | Munich    | D       | DanielHoffmannAyala | 1.0
Benoît Béranger          | CENIR, ICM                         | Paris     | FR      | benoitberanger | 1.0
Stephan Heunis           | Eindhoven University of Technology | Eindhoven | NL      | jsheunis | 1.0
Niklas Bürgi             | SNS, University of Zurich          | Zurich    | CH      | nbuergi | 1.0
Alexandre Sayal          | CIBIT, University of Coimbra       | Coimbra   | PT      | alexsayal | 1.0
Matthias Müller-Schrader | TNU, University of Zurich          | Zurich    | CH      | mms-neuro| 1.1
**- Add Entry here -**   | **- Add Entry here -**             | **Add**   | **Add** | **Add**      | 1.1               

(hereinafter referred to as "Contributor")

**Comment by mrikasper** [comment]
Or, even more comprehensive, including a link to the previous CLA version:

Contributor License Agreement
=============================
_Current Version: 1.1 (valid from 2022-09-01)_ | _[Previous version: 1.0 ](https://github.com/translationalneuromodeling/tapas/blob/v6.0.1/Contributor-License-Agreement.md) (before 2022-09-01)_

This AGREEMENT is made by and between the 

University of Zurich, Rämistrasse 71, 8006 Zürich, Switzerland   
(hereinafter referred to as "University of Zurich")

and 

each GitHub User listed in the following table:   

Name                     | Company/Institution/Address        | City      | Country | E-Mail/GitHub Username | CLA version signed
------------------------ | ---------------------------------- | --------- | ------- | ----------------------|---------------------
Lars Kasper              | TNU, University of Zurich          | Zurich    | CH      | mrikasper | 1.0
Eduardo Aponte           | TNU, University of Zurich          | Zurich    | CH      | tnutapas | 1.0
Daniel Hoffmann Ayala    | Technical University               | Munich    | D       | DanielHoffmannAyala | 1.0
Benoît Béranger          | CENIR, ICM                         | Paris     | FR      | benoitberanger | 1.0
Stephan Heunis           | Eindhoven University of Technology | Eindhoven | NL      | jsheunis | 1.0
Niklas Bürgi             | SNS, University of Zurich          | Zurich    | CH      | nbuergi | 1.0
Alexandre Sayal          | CIBIT, University of Coimbra       | Coimbra   | PT      | alexsayal | 1.0
Matthias Müller-Schrader | TNU, University of Zurich          | Zurich    | CH      | mms-neuro| 1.1
**- Add Entry here -**   | **- Add Entry here -**             | **Add**   | **Add** | **Add**      | 1.1               

(hereinafter referred to as "Contributor")

**Comment by mrikasper** [comment]
Or, more concise, just mentioning more contributors have signed another version:

Contributor License Agreement
=============================
_Current Version: 1.1 (valid from 2022-09-01)_ | _[Previous version: 1.0 ](https://github.com/translationalneuromodeling/tapas/blob/v6.0.1/Contributor-License-Agreement.md) (before 2022-09-01)_

This AGREEMENT is made by and between the 

University of Zurich, Rämistrasse 71, 8006 Zürich, Switzerland   
(hereinafter referred to as "University of Zurich")

and 

each GitHub User listed in the following table (*):   

Name                     | Company/Institution/Address        | City      | Country | E-Mail/GitHub Username 
------------------------ | ---------------------------------- | --------- | ------- | ----------------------
Matthias Müller-Schrader | TNU, University of Zurich          | Zurich    | CH      | mms-neuro
**- Add Entry here -**   | **- Add Entry here -**             | **Add**   | **Add** | **Add**                     

(*) Please note that additional contributors have signed a [previous version](https://github.com/translationalneuromodeling/tapas/blob/v6.0.1/Contributor-License-Agreement.md) of this agreement.

(hereinafter referred to as "Contributor")

**Comment by mrikasper** [comment]
@SaskiaBollmann we have now put an updated CLA in the development branch of TAPAS, could you please add your name to that one in a new pull request?

Thank you!

**Pull request closed without merging**
