### PR TITLE
noiseROI : remove "stats" toolbox depency by using SVD to perform PCA

### PR DESCRIPTION
**Pull request by benoitberanger**
Dear Lars,

The objective of the PR is to reduce TAPAS/PhysIO dependency on MATLAB non built-in function, as it was noted in https://github.com/translationalneuromodeling/tapas/issues/61#issuecomment-506635690

Here is an implementation of PCA using MATLAB's built-in `svd` function instead of the `pca` function from the "stats" toolbox.

I tested and compared the differences between the actual PCA outputs and this SVD implementation. For example COEFF(from PCA) - COEFF(from SVD) numerical differences is insignificant, lower than 10^-6 on my data sets.

Best,
Benoît

### CODE REVIEW

**Comment by mrikasper** [comment]
Dear Benoît,

this is indeed a great addition, thank you for the initiative.

I think it would be worthwhile to add the tests you did to check the equivalency of both methods, probably using simple numeric examples as well as some actual extracted WM/CSF time series. 

I recommend to use the Matlab unit testing framework for that, we started to use that for PhysIO, see, e.g., in our current [development branch](https://github.com/translationalneuromodeling/tapas/tree/development/PhysIO/tests).

There will be some more unit tests and integration tests in the upcoming release (End of August), if you want to wait to see more examples on how to use the framework in combination with PhysIO.

All the best,
Lars

**Comment by benoitberanger** [comment]
Dear Lars,

Having a permanent 'test script' in the repo to check the homogeneity of both PCA & SVD is a good idea. Also, this can provide an example about how to perform PCA without the toolbox for other MATLAB users (it took me a while to understand the relation between PCA and SVD).

I can try to write the UnitTests for the PCA part, as starting point for the whole `create_noise_roi` part. Or I wait until the text release. Up to you ! Let me know ?

Best,
Benoît

**Comment by mrikasper** [comment]
Dear Benoît,

the next release might be a bit too tight (likely next week). I suggest you can have a look at the new integration tests for the example scripts that come with the next release, and then start to work from there. They also test rather complicated examples, and the `create_noise_roi` part would be of this kind, too.

And I agree, the SVD/PCA equivalency might be a great unit test in itself. Maybe you can do it s.t. the Matlab implementation is the reference result (on a defined matrix, e.g., from the ROI extraction of WM/CSF, as well as some trivial example matrices) and your custom implementation is the actual result to be tested. Probably writing an own `tapas_physio_pca` function is the right way to capsulate the functionality.

Thank you so much for your efforts!

All the best,
Lars

**Comment by benoitberanger** [comment]
Dear Lars,

`tapas_physio_pca` will be an independent function for the UnitTest approach and for readability in the code of `create_noise_roi`.

Alright, I wait for next release to have some examples to rely on and work on it.

Best,
Benoît

**Comment by benoitberanger** [comment]
Sorry for the spam of GitHub notifications, it's the first time I rebase the upstream/master into my fork/dev-branch. It seems to be a bit messy when the PR is still opened...
Ben

**Comment by benoitberanger** [comment]
Dear Lars,

With cfac8b4, the PCA is wrapped around a function, which can be called and perform the new SVD built-in strategy or the previous strategy with "stats" toolbox.
The UnitTest is also created to get sure that both methods give the same result.
Side note : the input data is generated by randi(), it is not using a real dataset yet.

What do you think about this implementation ?

Best,
Benoît

**Comment by mrikasper** [comment]
Great work, thank you so much, Benoît, also for providing the unit tests. This really helps making the toolbox robust in the long run!

Your changes will be reflected in the current development branch of TAPAS now, and will be included in the next release.

Once again, thank you, also for your very valuable contributions in the forum.

All the best,
Lars

**Pull request merged**
